services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    environment:
      - CASSANDRA_CLUSTER_NAME=DreamStream
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1